### ISSUE TITLE
Favorites are hosed or stopped working

### ISSUE THREAD

**Issue by wilkinsbrian** [mikew/ss-plex.bundle#23]
Since the latest update, my favorites was polluted with favorites I never selected. Also, shows I used to have in my favorites no longer show any shows at all. Some favorites do work, but Search via the Web or iPad does not always show any shows.

**Comment by mikew** [comment]
http://forums.plexapp.com/index.php/topic/48412-rel-ss-plex/?p=478882
- Mike Wyatt

**Comment by wilkinsbrian** [comment]
Ok, so delete all favorites and start over? Not sure if this helps, but here is the dump from ss.log

2013-10-18 08:49:06,710 - ss.plex   - DEBUG Rendering listings for /shows/10673/episodes
2013-10-18 08:49:06,865 - ss.plex   - ERROR Error requesting /shows/10673/episodes
Traceback (most recent call last):
  File "/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-ins/ss-plex.bundle/Contents/Code/generic.py", line 84, in render_listings
    response  = JSON.ObjectFromURL(listings_endpoint, cacheTime = cache_time,
  File "/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-ins/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/api/parsekit.py", line 145, in ObjectFromURL
    method=method,
  File "/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-ins/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/api/networkkit.py", line 67, in _http_request
    req = self._core.networking.http_request(url, _args, *_kwargs)
  File "/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-ins/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/components/networking.py", line 422, in http_request
    return HTTPRequest(self._core, url, data, h, url_cache, encoding, errors, timeout, immediate, sleep, opener, follow_redirects, method)
  File "/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-ins/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/components/networking.py", line 147, in __init__
    self.load()
  File "/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-ins/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/components/networking.py", line 183, in load
    f = self._opener.open(req, timeout=self._timeout)
  File "/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-ins/Framework.bundle/Contents/Resources/Platforms/Shared/Libraries/urllib2_new.py", line 444, in open
    response = meth(req, response)
  File "/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-ins/Framework.bundle/Contents/Resources/Platforms/Shared/Libraries/urllib2_new.py", line 557, in http_response
    'http', request, response, code, msg, hdrs)
  File "/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-ins/Framework.bundle/Contents/Resources/Platforms/Shared/Libraries/urllib2_new.py", line 482, in error
    return self._call_chain(_args)
  File "/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-ins/Framework.bundle/Contents/Resources/Platforms/Shared/Libraries/urllib2_new.py", line 416, in _call_chain
    result = func(_args)
  File "/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-ins/Framework.bundle/Contents/Resources/Platforms/Shared/Libraries/urllib2_new.py", line 565, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 404: Not Found

**Comment by eppo120** [comment]
hey Mike, 

I've had the same issue, The link above is currently broken.
I've cleared my favorites, and all of the downloads.
I added 4 new favorites, and all seemed to be ok for a few hours. Then after that, I noticed my favorites went to 0, but I had 36 things downloading. Later on I had quite a few things added to my favorites.
If you can share how to fix it, that would be great, or let me know what you need to fix the issue.
Thank you very much for your work on this, its a great channel.
