### ISSUE TITLE
freebsd watch later feature error "IndexError: list index out of range"

### ISSUE THREAD

**Issue by edycus** [mikew/ss-plex.bundle#49]
In FreeBSD I keep getting the error "IndexError: list index out of range" when I choose the option of Watch Later. Love your work by the way. Awesome program. 

Is there a way to turn on additional debugging? 

Here is the error form ss.log
2015-10-01 03:34:38,463 - ss.cache      - DEBUG http://mightyupload.com/6bsa18v231uo/Freeshow.mp4.html-fname is stale
2015-10-01 03:34:38,469 - ss.consumer   - INFO  Found procedure for mightyupload.com
2015-10-01 03:34:38,470 - ss.consumer   - DEBUG Requesting http://mightyupload.com/6bsa18v231uo/Freeshow.mp4.html
2015-10-01 03:34:40,765 - ss.wizard     - ERROR Error on http://mightyupload.com/6bsa18v231uo/Freeshow.mp4.html
Traceback (most recent call last):
  File "/var/db/plexdata/Plex Media Server/Plug-ins/ss-plex.bundle/Contents/Libraries/Shared/ss/wizard.py", line 57, in sources
    cb(consumer)
  File "/var/db/plexdata/Plex Media Server/Plug-ins/ss-plex.bundle/Contents/Libraries/Shared/ss/downloader.py", line 144, in perform_download
    self.success  = self.really_download()
  File "/var/db/plexdata/Plex Media Server/Plug-ins/ss-plex.bundle/Contents/Libraries/Shared/ss/downloader.py", line 161, in really_download
    command  = self.download_command()
  File "/var/db/plexdata/Plex Media Server/Plug-ins/ss-plex.bundle/Contents/Libraries/Shared/ss/downloader.py", line 155, in download_command
    return globals()[self.strategy + '_strategy_command'](self)
  File "/var/db/plexdata/Plex Media Server/Plug-ins/ss-plex.bundle/Contents/Libraries/Shared/ss/downloader.py", line 15, in curl_strategy_command
    '--output',     dl.local_partfile
  File "/var/db/plexdata/Plex Media Server/Plug-ins/ss-plex.bundle/Contents/Libraries/Shared/ss/downloader.py", line 90, in local_partfile
    return self.local_file + '.part'
  File "/var/db/plexdata/Plex Media Server/Plug-ins/ss-plex.bundle/Contents/Libraries/Shared/ss/downloader.py", line 95, in local_file
    return os.path.join(self.destination, self.file_name)
  File "/var/db/plexdata/Plex Media Server/Plug-ins/ss-plex.bundle/Contents/Libraries/Shared/ss/downloader.py", line 78, in file_name
    consumed = self.consumer.file_name.encode()
  File "/var/db/plexdata/Plex Media Server/Plug-ins/ss-plex.bundle/Contents/Libraries/Shared/ss/consumer.py", line 100, in file_name
    self.fname = cache.fetch(self.file_cache_key, get_fname, expires = ttl)
  File "/var/db/plexdata/Plex Media Server/Plug-ins/ss-plex.bundle/Contents/Libraries/Shared/ss/cache.py", line 29, in fetch
    set(key, cb(), **kwargs)
  File "/var/db/plexdata/Plex Media Server/Plug-ins/ss-plex.bundle/Contents/Libraries/Shared/ss/consumer.py", line 95, in get_fname
    self.consume()
  File "/var/db/plexdata/Plex Media Server/Plug-ins/ss-plex.bundle/Contents/Libraries/Shared/ss/consumer.py", line 116, in consume
    self.run_step(self.proc.pop(0))
  File "/var/db/plexdata/Plex Media Server/Plug-ins/ss-plex.bundle/Contents/Libraries/Shared/ss/consumer.py", line 124, in run_step
    getattr(self, step['name'])(step['args'])
  File "/var/db/plexdata/Plex Media Server/Plug-ins/ss-plex.bundle/Contents/Libraries/Shared/ss/consumer.py", line 277, in asset_from_regex
    result     = expression.findall(haystack)[0]
IndexError: list index out of range
2015-10-01 03:34:40,818 - ss.downloader - DEBUG Running error callbacks
2015-10-01 03:34:40,853 - ss.bridge.download    - INFO  Dispatching download
2015-10-01 03:34:40,853 - ss.bridge.download    - INFO  Download queue empty
2015-10-01 03:34:59,527 - ss.plex       - DEBUG Rendering listings for /

Thank,
Eric

**Comment by enochian0117** [comment]
IndexError: list index out of range
2016-10-21 23:04:17,756 - ss.cache  - DEBUG http://vshare.eu/1twjyyvffmk5.htm-fname is stale
2016-10-21 23:04:17,786 - ss.consumer   - INFO  Found procedure for vshare.eu
2016-10-21 23:04:17,786 - ss.consumer   - DEBUG Requesting http://vshare.eu/1twjyyvffmk5.htm
2016-10-21 23:04:18,418 - ss.wizard - ERROR Error on http://vshare.eu/1twjyyvffmk5.htm
Traceback (most recent call last):
  File "C:\Users*\AppData\Local\Plex Media Server\Plug-ins\ss-plex.bundle\Contents\Libraries\Shared\ss\wizard.py", line 57, in sources
    cb(consumer)
  File "C:\Users*\AppData\Local\Plex Media Server\Plug-ins\ss-plex.bundle\Contents\Libraries\Shared\ss\downloader.py", line 144, in perform_download
    self.success  = self.really_download()
  File "C:\Users*\AppData\Local\Plex Media Server\Plug-ins\ss-plex.bundle\Contents\Libraries\Shared\ss\downloader.py", line 161, in really_download
    command  = self.download_command()
  File "C:\Users*\AppData\Local\Plex Media Server\Plug-ins\ss-plex.bundle\Contents\Libraries\Shared\ss\downloader.py", line 155, in download_command
    return globals()[self.strategy + '_strategy_command'](self)
  File "C:\Users*\AppData\Local\Plex Media Server\Plug-ins\ss-plex.bundle\Contents\Libraries\Shared\ss\downloader.py", line 15, in curl_strategy_command
    '--output',     dl.local_partfile
  File "C:\Users*\AppData\Local\Plex Media Server\Plug-ins\ss-plex.bundle\Contents\Libraries\Shared\ss\downloader.py", line 90, in local_partfile
    return self.local_file + '.part'
  File "C:\Users*\AppData\Local\Plex Media Server\Plug-ins\ss-plex.bundle\Contents\Libraries\Shared\ss\downloader.py", line 95, in local_file
    return os.path.join(self.destination, self.file_name)
  File "C:\Users*\AppData\Local\Plex Media Server\Plug-ins\ss-plex.bundle\Contents\Libraries\Shared\ss\downloader.py", line 78, in file_name
    consumed = self.consumer.file_name.encode()
  File "C:\Users*\AppData\Local\Plex Media Server\Plug-ins\ss-plex.bundle\Contents\Libraries\Shared\ss\consumer.py", line 100, in file_name
    self.fname = cache.fetch(self.file_cache_key, get_fname, expires = ttl)
  File "C:\Users*\AppData\Local\Plex Media Server\Plug-ins\ss-plex.bundle\Contents\Libraries\Shared\ss\cache.py", line 29, in fetch
    set(key, cb(), *_kwargs)
  File "C:\Users\_\AppData\Local\Plex Media Server\Plug-ins\ss-plex.bundle\Contents\Libraries\Shared\ss\consumer.py", line 95, in get_fname
    self.consume()
  File "C:\Users*\AppData\Local\Plex Media Server\Plug-ins\ss-plex.bundle\Contents\Libraries\Shared\ss\consumer.py", line 116, in consume
    self.run_step(self.proc.pop(0))
  File "C:\Users*\AppData\Local\Plex Media Server\Plug-ins\ss-plex.bundle\Contents\Libraries\Shared\ss\consumer.py", line 124, in run_step
    getattr(self, step['name'])(step['args'])
  File "C:\Users*\AppData\Local\Plex Media Server\Plug-ins\ss-plex.bundle\Contents\Libraries\Shared\ss\consumer.py", line 277, in asset_from_regex
    result     = expression.findall(haystack)[0]
IndexError: list index out of range

**Comment by ghost** [comment]
I get this same issue.  Have both Curl and Wget installed on the server.  Have also checked that it has correct permissions to the default download locations and everything should be working.
