### ISSUE TITLE
Downloaded Content Missing

### ISSUE THREAD

**Issue by Riverview** [mikew/ss-plex.bundle#55]

**Comment by Riverview** [comment]
File "C:\Users\Fairview 2\AppData\Local\Plex Media Server\Plug-ins\ss-plex.bundle\Contents\Libraries\Shared\ss\downloader.py", line 161, in really_download
    command  = self.download_command()
  File "C:\Users\Fairview 2\AppData\Local\Plex Media Server\Plug-ins\ss-plex.bundle\Contents\Libraries\Shared\ss\downloader.py", line 155, in download_command
    return globals()[self.strategy + '_strategy_command'](self)
  File "C:\Users\Fairview 2\AppData\Local\Plex Media Server\Plug-ins\ss-plex.bundle\Contents\Libraries\Shared\ss\downloader.py", line 15, in curl_strategy_command
    '--output',     dl.local_partfile
  File "C:\Users\Fairview 2\AppData\Local\Plex Media Server\Plug-ins\ss-plex.bundle\Contents\Libraries\Shared\ss\downloader.py", line 90, in local_partfile
    return self.local_file + '.part'
  File "C:\Users\Fairview 2\AppData\Local\Plex Media Server\Plug-ins\ss-plex.bundle\Contents\Libraries\Shared\ss\downloader.py", line 95, in local_file
    return os.path.join(self.destination, self.file_name)
  File "C:\Users\Fairview 2\AppData\Local\Plex Media Server\Plug-ins\ss-plex.bundle\Contents\Libraries\Shared\ss\downloader.py", line 78, in file_name
    consumed = self.consumer.file_name.encode()
  File "C:\Users\Fairview 2\AppData\Local\Plex Media Server\Plug-ins\ss-plex.bundle\Contents\Libraries\Shared\ss\consumer.py", line 100, in file_name
    self.fname = cache.fetch(self.file_cache_key, get_fname, expires = ttl)
  File "C:\Users\Fairview 2\AppData\Local\Plex Media Server\Plug-ins\ss-plex.bundle\Contents\Libraries\Shared\ss\cache.py", line 29, in fetch
    set(key, cb(), **kwargs)
  File "C:\Users\Fairview 2\AppData\Local\Plex Media Server\Plug-ins\ss-plex.bundle\Contents\Libraries\Shared\ss\consumer.py", line 95, in get_fname
    self.consume()
  File "C:\Users\Fairview 2\AppData\Local\Plex Media Server\Plug-ins\ss-plex.bundle\Contents\Libraries\Shared\ss\consumer.py", line 116, in consume
    self.run_step(self.proc.pop(0))
IndexError: pop from empty list
2016-01-31 17:45:11,207 - ss.cache	- DEBUG	http://vidzi.tv/prv58aftjzdw.html-fname is stale
2016-01-31 17:45:11,246 - ss.consumer	- INFO	Found procedure for vidzi.tv
2016-01-31 17:45:11,246 - ss.consumer	- DEBUG	Requesting http://vidzi.tv/prv58aftjzdw.html
2016-01-31 17:45:13,644 - ss.wizard	- ERROR	Error on http://vidzi.tv/prv58aftjzdw.html
Traceback (most recent call last):
  File "C:\Users\Fairview 2\AppData\Local\Plex Media Server\Plug-ins\ss-plex.bundle\Contents\Libraries\Shared\ss\wizard.py", line 57, in sources
    cb(consumer)
  File "C:\Users\Fairview 2\AppData\Local\Plex Media Server\Plug-ins\ss-plex.bundle\Contents\Libraries\Shared\ss\downloader.py", line 144, in perform_download
    self.success  = self.really_download()
  File "C:\Users\Fairview 2\AppData\Local\Plex Media Server\Plug-ins\ss-plex.bundle\Contents\Libraries\Shared\ss\downloader.py", line 161, in really_download
    command  = self.download_command()
  File "C:\Users\Fairview 2\AppData\Local\Plex Media Server\Plug-ins\ss-plex.bundle\Contents\Libraries\Shared\ss\downloader.py", line 155, in download_command
    return globals()[self.strategy + '_strategy_command'](self)
  File "C:\Users\Fairview 2\AppData\Local\Plex Media Server\Plug-ins\ss-plex.bundle\Contents\Libraries\Shared\ss\downloader.py", line 15, in curl_strategy_command
    '--output',     dl.local_partfile
  File "C:\Users\Fairview 2\AppData\Local\Plex Media Server\Plug-ins\ss-plex.bundle\Contents\Libraries\Shared\ss\downloader.py", line 90, in local_partfile
    return self.local_file + '.part'
  File "C:\Users\Fairview 2\AppData\Local\Plex Media Server\Plug-ins\ss-plex.bundle\Contents\Libraries\Shared\ss\downloader.py", line 95, in local_file
    return os.path.join(self.destination, self.file_name)
  File "C:\Users\Fairview 2\AppData\Local\Plex Media Server\Plug-ins\ss-plex.bundle\Contents\Libraries\Shared\ss\downloader.py", line 78, in file_name
    consumed = self.consumer.file_name.encode()
  File "C:\Users\Fairview 2\AppData\Local\Plex Media Server\Plug-ins\ss-plex.bundle\Contents\Libraries\Shared\ss\consumer.py", line 100, in file_name
    self.fname = cache.fetch(self.file_cache_key, get_fname, expires = ttl)
  File "C:\Users\Fairview 2\AppData\Local\Plex Media Server\Plug-ins\ss-plex.bundle\Contents\Libraries\Shared\ss\cache.py", line 29, in fetch
    set(key, cb(), **kwargs)
  File "C:\Users\Fairview 2\AppData\Local\Plex Media Server\Plug-ins\ss-plex.bundle\Contents\Libraries\Shared\ss\consumer.py", line 95, in get_fname
    self.consume()
  File "C:\Users\Fairview 2\AppData\Local\Plex Media Server\Plug-ins\ss-plex.bundle\Contents\Libraries\Shared\ss\consumer.py", line 116, in consume
    self.run_step(self.proc.pop(0))
IndexError: pop from empty list
2016-01-31 17:45:13,670 - ss.consumer	- INFO	.mp4
2016-01-31 17:45:13,680 - ss.cache	- DEBUG	http://vid.ag/ubtza9p1heth.html-url is stale
2016-01-31 17:45:13,723 - ss.consumer	- INFO	Found procedure for vid.ag
2016-01-31 17:45:13,723 - ss.consumer	- DEBUG	Requesting http://vid.ag/ubtza9p1heth.html
2016-01-31 17:45:15,872 - ss.consumer	- INFO	http://89.36.224.47/2t4w5fd5dvv5epwppptsy24fii3xthqjphhutxyu5udzjbxepcunc5fg5sea/v.mp4
2016-01-31 17:45:15,880 - ss.downloader	- INFO	['curl', '--location', '--referer', u'http://vid.ag/ubtza9p1heth.html', '--cookie', '', '--user-agent', 'Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_4_11; fr-fr) AppleWebKit/525.7+ (KHTML, like Gecko) Version/3.1.2 Safari/525.20.1', '--stderr', u'c:\\users\\fairvi~1\\appdata\\local\\temp\\-shows-12265-episodes-522324', '--output', u'C:\\Users\\Fairview 2\\Desktop\\TV Shows-SS Plex\\.mp4.part', '--limit-rate', u'2100K', 'http://89.36.224.47/2t4w5fd5dvv5epwppptsy24fii3xthqjphhutxyu5udzjbxepcunc5fg5sea/v.mp4']
2016-01-31 17:45:15,880 - ss.downloader	- DEBUG	Running start callbacks
2016-01-31 17:45:15,880 - ss.consumer	- INFO	.mp4
2016-01-31 17:47:51,528 - ss.plex	- DEBUG	Rendering listings for /
2016-01-31 17:50:44,621 - ss.plex	- DEBUG	Rendering listings for /
2016-01-31 17:52:48,059 - ss.plex	- DEBUG	Rendering listings for /
2016-01-31 18:02:10,838 - ss.plex	- DEBUG	Rendering listings for /
2016-01-31 18:05:05,933 - ss.downloader	- DEBUG	Running success callbacks
2016-01-31 18:05:05,934 - ss.consumer	- INFO	.mp4
2016-01-31 18:05:05,934 - ss.consumer	- INFO	.mp4
2016-01-31 18:05:06,000 - ss.bridge.download	- INFO	Dispatching download
2016-01-31 18:05:06,002 - ss.bridge.download	- INFO	Download queue empty
2016-01-31 18:05:06,002 - ss.downloader	- INFO	Finished downloading Movie
2016-01-31 18:05:09,042 - ss.plex	- DEBUG	Rendering listings for /
